### ISSUE TITLE
Assumptions for direction of incoming/outcoming fields

### ISSUE THREAD

**Issue by MakisH** [precice/preeco-orga#42]
Some normal fields require assumptions for flipping their direction: for example, reading/writing a heat flux, or reading/writing a normal velocity (mainly interesting in 1D-3D flow coupling).

We need to ensure that adapters follow the same assumption. For example, that writing is outgoing, and reading is incoming (and does the flipping).

Alternatively, we could make the flipping a configuration option for the respective fields (related to https://github.com/precice/preeco-orga/issues/36 and the schema).

**Comment by uekerman** [comment]
We could also do both: Define a standard and make it configurable.

It also makes somehow sense to me that:
- writing assumes an outward normal vector
- reading assumes an inward normal vector

Side note: There is a mathematical convention that the normal vector is typically pointing outward. So writing would be as expected, where reading feels like flipping the sign.

Could look as follows

```yml
interfaces:
  - mesh_name: Fluid-Mesh
    write_data:
      - name: Force
      - normal-direction: outwards # the default for write data
```
