### ISSUE TITLE
Add solver object for optional solver settings

### ISSUE THREAD

**Issue by uekerman** [precice/preeco-orga#45]
For some adapters, the adapter actually calls the solver. Then, typically, the adapter configuration needs to handle some solver details, such as where the solver configuration is. Even though the schema currently allows adding any objects, it could be helpful to define a standard object for these.

An example:

```yaml
participant_name: Fluid
precice_config_file_name: ../precice-config.xml
interfaces:
  - mesh_name: Fluid-Mesh
    write_data:
      - name: Force
 solver: # this object would be part of the schema (but not required)
    config_file_name: mymodel.yml # any objects could go here
```
